version: '3'
services:
  dispatcher:
    image: octoblu/meshblu-core-dispatcher:v19.0.4
    env_file: './meshblu-core-dispatcher.env'
    deploy:
      replicas: 3
    networks:
      - meshblu
  http:
    image: octoblu/meshblu-core-protocol-adapter-http:v5.4.8
    env_file: './meshblu-core-protocol-adapter-http.env'
    ports:
      - "1080:80"
    deploy:
      replicas: 3
    networks:
      - meshblu
  websocket:
    image: octoblu/meshblu-core-protocol-adapter-websocket:v4.1.2
    env_file: './meshblu-core-protocol-adapter-websocket.env'
    ports:
      - "2080:80"
    deploy:
      replicas: 1
    networks:
      - meshblu
  firehose:
    image: octoblu/meshblu-core-firehose-socket.io:v1.4.8
    env_file: './meshblu-core-firehose-socket.io.env'
    ports:
      - "3080:80"
    deploy:
      replicas: 1
    networks:
      - meshblu
  mongo:
    image: mongo
    volumes:
      - ./mongo-data:/data/db
    networks:
      - meshblu
  redis:
    image: redis
    volumes:
      - ./redis-data:/data
    networks:
      - meshblu
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - meshblu
networks:
  meshblu:
